# Generated by Django 5.2.6 on 2025-11-27 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCenterSupervisorShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('shift_1', 'Shift 1'), ('shift_2', 'Shift 2'), ('shift_3', 'Shift 3')], help_text='Shift for this supervisor assignment', max_length=10)),
                ('shift_start_time', models.TimeField(help_text='Shift start time (e.g., 09:00)')),
                ('shift_end_time', models.TimeField(help_text='Shift end time (e.g., 17:00)')),
                ('check_in_deadline', models.TimeField(help_text='Time by which primary supervisor should log in for this shift')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Work Center Supervisor Shift',
                'verbose_name_plural': 'Work Center Supervisor Shifts',
                'ordering': ['work_center__name', 'shift'],
            },
        ),
        migrations.AlterModelOptions(
            name='dailysupervisorstatus',
            options={'ordering': ['-date', 'work_center__name', 'shift'], 'verbose_name': 'Daily Supervisor Status', 'verbose_name_plural': 'Daily Supervisor Statuses'},
        ),
        migrations.RemoveIndex(
            model_name='dailysupervisorstatus',
            name='processes_d_date_511617_idx',
        ),
        migrations.AlterUniqueTogether(
            name='dailysupervisorstatus',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dailysupervisorstatus',
            name='shift',
            field=models.CharField(choices=[('shift_1', 'Shift 1'), ('shift_2', 'Shift 2'), ('shift_3', 'Shift 3')], default='shift_1', help_text='Shift for this status record', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailysupervisorstatus',
            name='active_supervisor',
            field=models.ForeignKey(help_text='Active supervisor for this work center today in this shift (default or backup)', on_delete=django.db.models.deletion.PROTECT, related_name='daily_active_supervisor_status', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dailysupervisorstatus',
            name='default_supervisor',
            field=models.ForeignKey(help_text='Default supervisor for this work center on this date and shift', on_delete=django.db.models.deletion.PROTECT, related_name='daily_default_supervisor_status', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='dailysupervisorstatus',
            unique_together={('date', 'work_center', 'shift')},
        ),
        migrations.AddIndex(
            model_name='dailysupervisorstatus',
            index=models.Index(fields=['date', 'work_center', 'shift'], name='processes_d_date_9541f3_idx'),
        ),
        migrations.AddField(
            model_name='workcentersupervisorshift',
            name='backup_supervisor',
            field=models.ForeignKey(help_text='Backup supervisor for this work center in this shift', on_delete=django.db.models.deletion.PROTECT, related_name='backup_shift_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workcentersupervisorshift',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shift_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workcentersupervisorshift',
            name='primary_supervisor',
            field=models.ForeignKey(help_text='Primary supervisor for this work center in this shift', on_delete=django.db.models.deletion.PROTECT, related_name='primary_shift_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workcentersupervisorshift',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_shift_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workcentersupervisorshift',
            name='work_center',
            field=models.ForeignKey(help_text='Process (work center) for this supervisor assignment', on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_shifts', to='processes.process'),
        ),
        migrations.AddIndex(
            model_name='workcentersupervisorshift',
            index=models.Index(fields=['work_center', 'shift', 'is_active'], name='processes_w_work_ce_9cba1b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workcentersupervisorshift',
            unique_together={('work_center', 'shift')},
        ),
    ]
