# Generated by Django 5.2.6 on 2025-11-27 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0003_batchprocesscompletion_batchreceiptverification_and_more'),
        ('processes', '0002_workcentersupervisorshift_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MOShiftConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('shift_1', 'Shift 1'), ('shift_2', 'Shift 2'), ('shift_3', 'Shift 3')], help_text='Shift identifier', max_length=10)),
                ('shift_start_time', models.TimeField(help_text='Shift start time (e.g., 09:00)')),
                ('shift_end_time', models.TimeField(help_text='Shift end time (e.g., 17:00)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this shift is currently active for this MO')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mo_shifts', to=settings.AUTH_USER_MODEL)),
                ('mo', models.ForeignKey(help_text='MO for this shift configuration', on_delete=django.db.models.deletion.CASCADE, related_name='shift_configurations', to='manufacturing.manufacturingorder')),
            ],
            options={
                'verbose_name': 'MO Shift Configuration',
                'verbose_name_plural': 'MO Shift Configurations',
                'ordering': ['mo', 'shift'],
                'indexes': [models.Index(fields=['mo', 'shift', 'is_active'], name='manufacturi_mo_id_ed7740_idx')],
                'unique_together': {('mo', 'shift')},
            },
        ),
        migrations.CreateModel(
            name='MOSupervisorOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('shift_1', 'Shift 1'), ('shift_2', 'Shift 2'), ('shift_3', 'Shift 3')], help_text='Shift for this override', max_length=10)),
                ('override_reason', models.TextField(blank=True, help_text='Reason for overriding the default supervisors')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this override is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backup_supervisor', models.ForeignKey(help_text='Backup supervisor for this MO + process + shift', on_delete=django.db.models.deletion.PROTECT, related_name='mo_backup_overrides', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mo_overrides', to=settings.AUTH_USER_MODEL)),
                ('mo', models.ForeignKey(help_text='MO for this supervisor override', on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_overrides', to='manufacturing.manufacturingorder')),
                ('primary_supervisor', models.ForeignKey(help_text='Primary supervisor for this MO + process + shift', on_delete=django.db.models.deletion.PROTECT, related_name='mo_primary_overrides', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(help_text='Process (work center) for this override', on_delete=django.db.models.deletion.CASCADE, related_name='mo_supervisor_overrides', to='processes.process')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_mo_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MO Supervisor Override',
                'verbose_name_plural': 'MO Supervisor Overrides',
                'ordering': ['mo', 'process', 'shift'],
                'indexes': [models.Index(fields=['mo', 'process', 'shift', 'is_active'], name='manufacturi_mo_id_6e46f4_idx')],
                'unique_together': {('mo', 'process', 'shift')},
            },
        ),
        migrations.CreateModel(
            name='SupervisorChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_reason', models.CharField(choices=[('initial_assignment', 'Initial Assignment'), ('attendance_absence', 'Attendance - Primary Absent'), ('mid_process_change', 'Mid-Process Change by PH'), ('shift_change', 'Shift Change'), ('manual_override', 'Manual Override'), ('both_unavailable', 'Both Primary and Backup Unavailable')], help_text='Reason for supervisor change', max_length=50)),
                ('change_notes', models.TextField(blank=True)),
                ('shift', models.CharField(blank=True, choices=[('shift_1', 'Shift 1'), ('shift_2', 'Shift 2'), ('shift_3', 'Shift 3')], help_text='Shift when this change occurred', max_length=10, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('process_status_at_change', models.CharField(blank=True, help_text='Status of process execution when supervisor changed', max_length=20)),
                ('changed_by', models.ForeignKey(blank=True, help_text='User who initiated this change (null for automatic changes)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_supervisor_changes', to=settings.AUTH_USER_MODEL)),
                ('from_supervisor', models.ForeignKey(blank=True, help_text='Previous supervisor (null if first assignment)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_changes_from', to=settings.AUTH_USER_MODEL)),
                ('mo_process_execution', models.ForeignKey(help_text='Process execution for this supervisor change', on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_changes', to='manufacturing.moprocessexecution')),
                ('to_supervisor', models.ForeignKey(help_text='New supervisor', on_delete=django.db.models.deletion.PROTECT, related_name='supervisor_changes_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supervisor Change Log',
                'verbose_name_plural': 'Supervisor Change Logs',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['mo_process_execution', 'changed_at'], name='manufacturi_mo_proc_d6b2aa_idx'), models.Index(fields=['to_supervisor', 'changed_at'], name='manufacturi_to_supe_1ea58c_idx'), models.Index(fields=['change_reason'], name='manufacturi_change__369a57_idx')],
            },
        ),
    ]
